# MongoDB Config
spring.data.mongodb.uri=mongodb+srv://aravindstrikes278_db_user:bmvA2URMaxd4aDPQ@cluster0.okw0nps.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=inticivi
spring.data.mongodb.auto-index-creation=true

# JWT Config
jwt.secret=dVWqMRyVBci2ozUNXi0prwUvBE4Wu7z9QOTiQPoX1f0=
jwt.expiration-ms=86400000
server.port=8080